### ISSUE TITLE
1.16.5只能使用Java16+

### ISSUE THREAD

**Issue by Kasualix** [ThinkingStudios/BetterSodiumVideoSettings-Forge#2]
如题。

**Comment by TexBlock** [comment]
正在修复（目前尝试移到Architectury Loom 0.7.x）~~，稍后会发布一个修复版本~~
~~由于 Architectury Loom 0.10.0 仅支持 java16+ ，暂无法修复~~
~~目前测试 Architectury Loom <0.10.0.185 支持 java 11 及以下~~

**Comment by TexBlock** [comment]
暂无法修复，此issue关闭
将会在找到解决方法后重新打开此issue

**Comment by ghost** [comment]
just set the java compatibility Level in bsvsb.mixins.json to 8 and it'll work.

**Comment by TexBlock** [comment]
已在[BRVSB-mc1.16.x-v1.0.2-Hotfix2](https://modrinth.com/mod/brvsb/version/mc1.16.x-v1.0.2-Hotfix2)修复

Fixed in [BRVSB-mc1.16.x-v1.0.2-Hotfix2](https://modrinth.com/mod/brvsb/version/mc1.16.x-v1.0.2-Hotfix2)
