### ISSUE TITLE
[1.16.5] Crash when clicking the options button.

### ISSUE THREAD

**Issue by ghost** [ThinkingStudios/BetterSodiumVideoSettings-Forge#3]
> Version that I used - [BRVSB-mc1.16.x-v1.0.2-Hotfix](https://modrinth.com/mod/brvsb/version/mc1.16.x-v1.0.2-Hotfix)
> - [latest.log](https://github.com/TexTrueStudio/BetterSodiumVideoSettings-Forge/files/9996290/latest.log)

**Comment by TexBlock** [comment]
OptiForge？Why install it, rubidium and optifine are not compatible.

**Comment by ghost** [comment]
Oh, is that causing the problem?
I completely forget that both rubidium and optifine were not compatible. together.
My bad.
