### ISSUE TITLE
1.16 依赖 rubidium 0.6 错误，最新版本是 0.2.10

### ISSUE THREAD

**Issue by SettingDust** [ThinkingStudios/BetterSodiumVideoSettings-Forge#4]
https://github.com/TexTrueStudio/BetterSodiumVideoSettings-Forge/blob/1.16.x-forge/dev/src/main/resources/META-INF/mods.toml#L34

**Comment by TexBlock** [comment]
我才看见这个issue（（（
一会修完就发布hotfix（

**Comment by TexBlock** [comment]
已发布mc1.16.5-v1.0.3-Hotfix
