### ISSUE TITLE
与TRO冲突

### ISSUE THREAD

**Issue by SulfuricM** [ThinkingStudios/BetterSodiumVideoSettings-Forge#5]
游戏版本1.18.2
铷版本0.5.4
铷扩展版本0.4.17
TRO版本1.0.4
BRVSB版本1.0.3
装了TRO后点按钮无法打开铷视频设置界面

**Comment by TexBlock** [comment]
发一下游戏日志，谢谢

**Comment by SulfuricM** [comment]
[latest.log](https://github.com/TexTrueStudio/BetterSodiumVideoSettings-Forge/files/10968989/latest.log)

[debug.log](https://github.com/TexTrueStudio/BetterSodiumVideoSettings-Forge/files/10968990/debug.log)

**Comment by TexBlock** [comment]
已在 [mc1.18.x-v1.0.4](https://modrinth.com/mod/brvsb/version/mc1.18.x-v1.0.4) 修复
