### ISSUE TITLE
[1.16.5] [BUG] Incompatible with TRO

### ISSUE THREAD

**Issue by Kasualix** [ThinkingStudios/BetterSodiumVideoSettings-Forge#6]
![image](https://user-images.githubusercontent.com/110756250/226928848-654f8e40-bd4b-4aa9-a239-daee0c25cf50.png)

一按就崩：
https://pastebin.ubuntu.com/p/8vtpwXhWSy/

**Comment by TexBlock** [comment]
应该是和TRO的兼容性出了问题，我这边测试只是无法进入铷的视频界面

**Comment by Kasualix** [comment]
老版本好像没这个问题，Hotfix2。

**Comment by TexBlock** [comment]
> 老版本好像没这个问题，Hotfix2。

Hotfix2 和 TRO 兼容？

**Comment by Kasualix** [comment]
大概吧

**Comment by Kasualix** [comment]
话说你beta到release更了啥就让它不兼容了？

**Comment by TexBlock** [comment]
> 话说你beta到release更了啥就让它不兼容了？

可能是这里：
https://github.com/TexTrueStudio/BetterSodiumVideoSettings-Forge/commit/ed5a08e466b3d2b4d6f7fd1b1f1f0a8474b0a398#diff-48af6123e91e17a024d298a90d8e11aa405c9e9175a816d674592ed3189bb30e

**Comment by TexBlock** [comment]
我在尝试回滚更改到v1.0.2-Hotfix2

**Comment by TexBlock** [comment]
已修复 https://modrinth.com/mod/brvsb/version/mc1.16.5-v1.0.4

**Comment by Kasualix** [comment]
CurseForge pls

**Comment by TexBlock** [comment]
> CurseForge pls

uploaded
